FROM hyperdx/agent:latest

# Añadir configuraciones personalizadas
COPY hyperdx-config.yml /etc/hyperdx-agent/hyperdx.yaml

# Variable de entorno necesaria para el agente
ENV HDX_API_KEY=your_hyperdx_api_key
